<a href="https://colab.research.google.com/github/Gayathri-achari/DL-COLAB/blob/Matrices/multiply_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


In [3]:
def generate_data(num_samples, matrix_size):
    X1 = np.random.rand(num_samples, matrix_size, matrix_size)
    X2 = np.random.rand(num_samples, matrix_size, matrix_size)
    Y = np.array([np.matmul(x1, x2) for x1, x2 in zip(X1, X2)])
    return X1, X2, Y

matrix_size = 3  # Example size of the matrices
num_samples = 1000  # Number of training samples

X1_train, X2_train, Y_train = generate_data(num_samples, matrix_size)


In [4]:
def create_model(matrix_size):
    input_shape = (matrix_size, matrix_size)

    model = keras.Sequential([
        layers.Input(shape=input_shape, name='input1'),
        layers.Flatten(),
        layers.Dense(matrix_size * matrix_size, activation='linear'),
        layers.Reshape((matrix_size, matrix_size))
    ])

    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

model = create_model(matrix_size)


In [5]:
history = model.fit(
    X1_train,
    Y_train,
    epochs=10,
    batch_size=32,
    validation_split=0.1
)


Epoch 1/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 1.1403 - val_loss: 0.9593
Epoch 2/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9085 - val_loss: 0.7716
Epoch 3/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7235 - val_loss: 0.6261
Epoch 4/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5955 - val_loss: 0.5143
Epoch 5/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4783 - val_loss: 0.4280
Epoch 6/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4070 - val_loss: 0.3612
Epoch 7/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3434 - val_loss: 0.3099
Epoch 8/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2994 - val_loss: 0.2701
Epoch 9/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2475 - val_loss: 0.2401
Epoch 10/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2350 - val_loss: 0.2168


In [6]:
X1_test, X2_test, Y_test = generate_data(100, matrix_size)
loss = model.evaluate(X1_test, Y_test)
print(f'Test loss: {loss}')


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2464 
Test loss: 0.24975375831127167


In [7]:
predictions = model.predict(X1_test)
print("Predicted:", predictions[0])
print("Actual   :", Y_test[0])


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
Predicted: [[0.6338152  0.5910124  0.47298926]
 [0.60752267 0.67211854 0.48750293]
 [0.8043518  0.73610514 1.0634193 ]]
Actual   : [[1.49873588 0.80331152 1.41385112]
 [0.80014766 0.69881076 1.08623615]
 [0.7832651  0.26816477 0.55988778]]
